### ISSUE TITLE
Open Source Design blog on Medium (Join the Medium publication here!)

### ISSUE THREAD

**Issue by razetime** [opensourcedesign/organization#17]
I have created a Medium publication for Open source, design, which could help our organization reach more people, and contribute more to the design community.
It lives at https://medium.com/open-source-design, and I think we can put all our posts in the http://opensourcedesign.net/articles/ page into this medium page.
Anyone interested in publishing, or have any ideas?

**Comment by plastelina** [comment]
great one! :+1: 

my account: https://medium.com/@karolinaferenz (if you want to follow me) , I've got several publications in draft...waiting for my laptop to come back form repair and will be ready to publish :).

**Comment by simonv3** [comment]
I'm very curious about how some other people on here feel about Medium, considering it is not very Open Sourcey at all, I think Medium would even own the articles?

I'm all for writing articles and publishing them on our own feed and then copying them to medium. But I think we should try to make sure we at least have our own copies of everything.

**Comment by plastelina** [comment]
I think medium is one of the best ways to reach out to designers, I met epic people there! Fantastic UX/UI, interaction and web designers as well as developers. In my opinion, looking at this subject - that open source should only use open source make it CLOSE SOURCE, because you dont have an option to actually chat to people and TELL them that there is an OPEN SOURCE community for designer...I only found out 2 years ago open source and it was by an accident. 

Also...why everything have to be discussed to the level of insanity? 
If you dont like medium - don't use it, find alternative and share it here! Simples.
If you like it - use it.

Yes, I used to use gimp and few other programs but that was over 15 years ago and these were just beginning of what is happening now. Now open source design tools are epic and they need more shout out - medium is great for that.

**Comment by elioqoshi** [comment]
Medium supports Creative Commons, so that's enough reason for me to support them (apart their new ugly logo honestly)

**Comment by simonv3** [comment]
@plastelina Open Source is a Very Opinionated Community. The divergent opinions about what open software means is what attracts people to it. Debate and conversation about how to best make software free is a critical part of the conversation. Telling people to not have that conversation is not productive because it *will* happen. Open Source, like everything in life, is a series of compromises. When you're talking to people working in Open Source, this conversation is going to happen - if I hadn't brought it up, someone else would have. 

And like I said - *I'm for doing this*, as long as we make sure that anything written under the Open Source Design banner also has a home on our own site. There's a variety of reasons for this, and Medium being or not being Open Source is just one of them. Medium is a venture backed company that - as far as I'm aware - doesn't make any money yet. What if, like Rdio, it shuts down next week? Or, like Twitter, is starting to have to lay off its employees because it doesn't make enough money? Both Twitter and Rdio are fantastic products and have changed things for a lot of people. Medium is like that too. But even if it supports CC like @elioqoshi mentions, I think owning the things written under the OSD name is **not** something that I would label insane.

@elioqoshi do you have a link for the support of creative commons?

**Comment by simonv3** [comment]
Also, please, if not being able to write on Medium is what's been preventing people writing about Open Source Design, please start writing on Medium. If you tell me you wrote it, I'll copy it over to the articles myself.

**Comment by elioqoshi** [comment]
@simonv3 here:
http://creativecommons.org/weblog/entry/45495

**Comment by simonv3** [comment]
@elioqoshi That's awesome, thanks!

**Comment by rdbartlett** [comment]
[I wrote a post to share my design process](http://blog.loomio.org/2015/07/07/design-for-developers/). I use a lot of proprietary software to make open source software, heh. 

I'm happy to copy it over to Medium to get this publication started if y'all think it fits.

**Comment by jancborchardt** [comment]
We could crosspost yeah, but the original posts should always be on opensourcedesign.net. These pages are tools to reach more people, but for actual writing and publishing there’s great open source platforms already like [Ghost](https://ghost.org/).

**Comment by simonv3** [comment]
QB on IRC just pointed me to the fact that you can easily import things to Medium here: https://medium.com/p/import

**Comment by simonv3** [comment]
@rdbartlett I think that'd be cool! Though, in the spirit of Medium being about written things (is it?) do you have a transcript version of the talk? I'm not sure what the general consensus is on posting videos on Medium?

**Comment by rdbartlett** [comment]
@simonv3 it's mostly me demonstrating how I use my particular combination of tools, so it doesn't translate too well into text.

**Comment by rdbartlett** [comment]
@razetime I'm wondering if, rather than just porting my story across to Medium, I reframe it into a sort of introductory blog post? Like, hi I'm Rich, this is why I care about open source design, here's some talks and articles and projects I've had a hand in...

**Comment by rdbartlett** [comment]
I'm imagining that lots of people in this community could do a similar thing. Something more engaging, sharable, and narrative-based than the brief bios we already have.

**Comment by simonv3** [comment]
That would be pretty cool. We could potentially stagger the posts as well - just for continuous returns? We can also create a special layout on our website for this kind of story "profiles" or something.

@razetime @rdbartlett @plastelina @elioqoshi would you all be interested in spearheading some sort of initiative like this? Maybe create a list of questions that people should try to answer? Provide some example posts?

**Comment by simonv3** [comment]
(Also @razetime if you could share some publishing rights to anyone who's interested in maintaining this that would be grand).

**Comment by rdbartlett** [comment]
@plastelina I'd love to read about how you accidentally discovered open source :dancer:

**Comment by rdbartlett** [comment]
So instead of doing that, I just wrote a totally new post. Very keen to hear feedback :)

https://medium.com/@richdecibels/open-source-design-just-steal-everything-5c44ca793721#.z2is2ra8r

@razetime do you want to add me as an editor on that publication?

**Comment by elioqoshi** [comment]
@simonv3 Yes, I'd love to!

**Comment by razetime** [comment]
Sorry that I did not respond, but I was sleeping at the time at the replies
came in.
I'll make sure that everybody who is interested, is added.
Any more thoughts?

**Comment by razetime** [comment]
Everyone who is interested can join, as a writer. If you write better posts, you will become an editor. @plastelina @rdbartlett You're in.

**Comment by razetime** [comment]
And @simonv3 I'd like to take an initiative like this.
We can write about how we discovered open source, and (possibly) design.
Everybody who wants to publish, just keep one thing in mind: Write about **Open Source** Design.

**Comment by plastelina** [comment]
@simonv3 thank you for clarifying the issue for me :D. You are missing the point, every community is strongly opinionated. What I was trying to point out is that you, pretty much always diss a lot of initiatives to push open source design to the open world. I'm not trying to dismiss what Open Source sand for, I'm trying to come up with an ideas to spread the word and as you mentioned yourself - it will attract specific people, not every designer / developer will join. It's a basic PR ( as in publish relations not push repository ;))move. /end of rant ;). 

Also, there was no debate about opening twitter account and there is an issue about opening a medium account!? C'mon, medium is actually one of those rare tool that attracts designers and yes, it might be shut down at some point in the future, but why not use its capacity to spread the word and educate people what open source is. There are a lot of open source contributors to medium already.

I'm writing articles on Medium as myself, but I'm happy to contribute to Open Source Design Medium account. ARGH! need my computer back, feeling like I've lost an arm...

**Comment by razetime** [comment]
@plastelina no need to hurry, let's be slow and steady. And plus, Medium IS
making money, with native advertising in posts, but I still think that is not
enough. So let's keep an original with ourselves, and put a copy of our
articles on Medium.

IF you allow, @simonv, we can keep some of the articles exclusive to medium,
though.

> On Nov 21 2015, at 3:09 pm, karolina ferenz &lt;notifications@github.com&gt;
wrote:  

>

> [@simonv3](https://github.com/simonv3) thank you for clarifying the issue
for me :D. You are missing the point, every community is strongly opinionated.
What I was trying to point out is that you, pretty much always diss a lot of
initiatives to push open source design to the open world. I'm not trying to
dismiss what Open Source sand for, I'm trying to come up with an ideas to
spread the word and as you mentioned yourself - it will attract specific
people, not every designer / developer will join. It's a basic PR ( as in
publish relations not push repository ;))move. /end of rant ;).

>

> Also, there was no debate about opening twitter account and there is an
issue about opening a medium account!? C'mon, medium is actually one of those
rare tool that attracts designers and yes, it might be shut down at some point
in the future, but why not use its capacity to spread the word and educate
people what open source is. There are a lot of open source contributors to
medium already.

>

> I'm writing articles on Medium as myself, but I'm happy to contribute to
Open Source Design Medium account. ARGH! need my computer back, feeling like
I've lost an arm...

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/opensou
rcedesign/organization/issues/17#issuecomment-158617101).![](https://github.co
m/notifications/beacon/AKgUl5v7fanikKIGqCAUv67Bd86s4qr8ks5pIDNNgaJpZM4GmdA8.gi
f)

**Comment by simonv3** [comment]
@razetime This isn't about me allowing it or not, this is about building a community consensus on whether we should move forward with something. 

@plastelina it sounds like we should hash things out in some form of private conversation - I never meant to make it sound like I'm dissing ideas - in fact, I feel like I've been supportive of most of the initiatives proposed, just cautious about most of the ones that aren't open source. Please feel free to DM me on IRC or on Twitter if you want to continue this conversation without clogging up everyone's notifications / emails.

We're not Anonymous (rag tag bunch of people with only the loosest affiliation), and I don't think we should be. I think it's important that *every one in the community gets an opportunity to voice concerns*, and that the Open Source Design community needs to at least have some form of consensus on what it stands for. This is exactly why I think we need some more structure - I've raised issues on bylaws, codes of conducts, how to reach consensus before. Please please please give your input [on those issues](https://github.com/opensourcedesign/organization/issues). If the majority of people in this group feel that we should use closed source tools like Slack and Medium because they'll achieve those [goals](http://opensourcedesign.net/about/) better, then maybe we should. But if that majority of people is silent and doesn't speak up about these things, how are the people doing things meant to know that?

(This is why I put the logo thing up to a vote, it allows quiet people to give their opinion without having to get into this conversation)

I have no idea who controls the Twitter account. We should have probably had a public conversation about that too.

**Comment by simonv3** [comment]
@rdbartlett I like that post! @razetime thanks for assigning people editors. We should possibly link the posts to Twitter as well?

**Comment by skddc** [comment]
> IF you allow, @simonv, we can keep some of the articles exclusive to medium, though.

Why would you keep something *exclusive* to Medium, when it's easy not to?

**Comment by GarthDB** [comment]
I've been publishing articles to both opendesign.foundation and [Medium](https://medium.com/design-open). It works out well us, but we go where the designers are and don't really have the requirement of only using open source projects.

**Comment by simonv3** [comment]
And maybe we *do* want to be more like Anonymous (everyone does what they
think is best), and let the Open Design Foundation be the structured entity?

**Comment by GarthDB** [comment]
I'm not sure how you go about deciding that. It seems like most people are acting like you're in charge Simon but it seems like you're trying hard to not have anyone in charge.



—

**Comment by skddc** [comment]
You lost me there. What's the discussion now?

**Comment by GarthDB** [comment]
I think we should build some bike sheds.



—

**Comment by simonv3** [comment]
I've got some yaks that need shaving.

**Comment by simonv3** [comment]
> Why would you keep something exclusive to Medium, when it's easy not to?

@skddc I had completely missed this. I agree. Is there a reason that we'd keep articles exclusively on Medium?

@rdbartlett do you mind if we cross post your post to the Articles section here?

**Comment by rdbartlett** [comment]
Certainly, so whatever you like with the content, just link back to me :)

For the record, I'm 100x more motivated to write and publish on Medium over
any other platform I've used. It's just a delightful and effective tool.

**Comment by simonv3** [comment]
Plus, I like that it still gives the authors a bit more credit - the current Articles are pretty anonymous.

**Comment by evalica** [comment]
We are using lots of proprietary tools in our day to day life, so finding open alternatives can be hard, sometimes impossible. We could decide not to use them at all, but if some people are more productive or experimented in using them, it's fine. 

But I agree, if it's something done in the name and in the interest of Open Source Design community, it needs to be cross-posted here. In order to keep things findable for everyone and to expand this community, we need to have a central hub. In order to keep things simpler I prefer to have only one place that I need to monitor. If people don't want to cross-post here, than maybe they should keep those articles in private blogs.

**Comment by evalica** [comment]
We could find ways if needed to automate the cross-posting from Medium to our website.

**Comment by skddc** [comment]
> Certainly, so whatever you like with the content, just link back to me :) For the record, I'm 100x more motivated to write and publish on Medium over any other platform I've used. It's just a delightful and effective tool.

I've heard that a lot, and there are actually open-source versions of their editor UI. Maybe someone can whip sth up, so that the experience is as nice when writing on the OSD site first. ;)

> We could find ways if needed to automate the cross-posting from Medium to our website.

That should be possible! Unfortunately (just looking at the first feed real quick, no deeper research), it looks like they [only provide teasers via RSS](https://medium.com/feed/open-source-design), which removes the obvious option for syndication and kind of makes them look even more like a walled garden to me. :/

**Comment by razetime** [comment]
@skddc There is a nice markdown editor, called http:// prose.io, which
gives you a simply amazing writing experience. I would not say that there
is a reason to keep any of the articles **only** on Medium though.

**Comment by jancborchardt** [comment]
There’s also, as mentioned above, the simple blogging platform https://ghost.org – nicely designed and runs on open source.

Of course we could just use Medium and Slack etc. in this community as well but then where’s the point in our work if we don’t use it – especially when there _are_ well-designed alternatives?

**Comment by GarthDB** [comment]
The most obvious issue to using something like ghost is hosting. Paid hosting introduces money, which doesn't guarantee complications, but it has potential to.

**Comment by skddc** [comment]
Ghost offers hosting and is itself a design-focussed open source project. I'm sure they'd gladly host OSD for free if you ask them.

**Comment by GarthDB** [comment]
If you can get free hosting that would be awesome.

**Comment by simonv3** [comment]
@skddc @GarthDB I just pointed out that we could potentially also reach out to the Sandstorm people for hosting, and then we can host all sorts of things on their grains as well -> #19.

@bnvk and @jancborchardt asked in https://github.com/opensourcedesign/opensourcedesign.github.io/pull/33 whether we should post on the OSD website first before posting to Medium - or at least saying on Medium *This post was original published on OSD* (or some such).

**Comment by GarthDB** [comment]
Hey - [Wordpress.com](https://developer.wordpress.com/calypso/) is opensource now too, just to muddy the waters further.

**Comment by jancborchardt** [comment]
@GarthDB »now« – you’re kidding, right? ;) Wordpress has been open source since forever.

**Comment by GarthDB** [comment]
@jancborchardt Wordpress, yes. Wordpress.com, no, until now.

**Comment by aoloe** [comment]
hey guys, this is a ticket about putting something on medium, not a way to chit chat...
really, you urgently need to get to an agreement on which chat platform you want to use and stop filling up everybody's inbox / github dashboard!
(and i'd prefer not to unsubscribe the repositories... but i will have to if i keep on getting 200+ pings a day from you!)

**Comment by jancborchardt** [comment]
@aoloe you can unsubscribe from individual issues – right sidebar, »unsubscribe« button. Sorry though for getting off the rails.

**Comment by aoloe** [comment]
@jancborchardt it's a general problem for opensourcedesign lately.
please count the number of "chatty" replies to this topic and put the number in here.
if it's painful to count, it's because you're doing it wrong.

**Comment by GarthDB** [comment]
@aoloe There's not really a right or a wrong way to have an open discussion; you may not like how it happens, but that doesn't make it wrong.

**Comment by simonv3** [comment]
@jancborchardt I think @GarthDB meant more specifically that wordpress.com is open source (the hosting platform), as opposed to just the wordpress blog publishing platform. 

Hey @aoloe - you could suggest changing how we discuss things in the [bylaws](#12) conversation, or create a new issue for this specifically. I actually don't think there's too much chit-chat going on in this thread (https://github.com/opensourcedesign/opensourcedesign.github.io/issues/16 is a different issue).

**Comment by aoloe** [comment]
@simonv3 and @GarthDB , there's not right way, no.
but there are better and worse tools for running a specific conversation.
i'm just a visitor in this community and i won't tell you, how you should run a conversation.
i can only tell you that there are many signs that show that this conversation does not run through the right medium.
that was my last message in this topic. and i will unsubscribe now, eventually missing posts that indeed are about the best way to manage the side publishing on medium.

**Comment by skddc** [comment]
Just in time: http://ma.tt/2015/11/dance-to-calypso/ ;)

**Comment by razetime** [comment]
@skddc Do you have a Medium account? If so, I'll add you, and approve your story.  If not, then tell me how you'd like your story to look like, on Medium.

**Comment by skddc** [comment]
@razetime Huh? I just linked Matt announcing a completely new writing UI for WordPress and moving to a node.js/React client with a WP API. ;)

**Comment by skddc** [comment]
By the way, that only works with WordPress.com at the moment, because WP Stable doesn't have the API yet.

https://desktop.wordpress.com/

**Comment by jancborchardt** [comment]
So ever since we opened the account, there is no single post on it: https://medium.com/open-source-design

As said in https://github.com/opensourcedesign/opensourcedesign.github.io/issues/27#issuecomment-293953812:
> As for the [Medium account](https://medium.com/open-source-design) we also have floating around which was set up by @razetime, I would say we get rid of it since it has no articles, and to promote our own articles page and as we already support a lot of proprietary platforms. What do you think?

**Comment by elioqoshi** [comment]
Was not aware we had a Medium account. I suggest we get rid of it as the irony of using another proprietary platform is too overwhelming here.

**Comment by jancborchardt** [comment]
I mailed @razetime about removing this Medium account and the Facebook account (https://github.com/opensourcedesign/opensourcedesign.github.io/issues/27) :)

**Comment by jancborchardt** [comment]
Closing this just like the Facebook page issue. We should remove that account too @razetime 

See also https://github.com/opensourcedesign/organization/pull/86 update of our community platform list.

**Comment by jancborchardt** [comment]
Closing this just like the Facebook page issue. We should remove that account too @razetime @plastelina @rdbartlett 

See also https://github.com/opensourcedesign/organization/pull/86 update of our community platform list.
