### ISSUE TITLE
Domain consistency

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/organization#18]
Hi, 

I think we need to agree on what naming we should use when creating/adding external services in the benefit of our community. 

For example: 
In the Medium proposal (https://github.com/opensourcedesign/organization/issues/17) why is it called 
- https://medium.com/open-source-design ?

When we have: 
- http://opensourcedesign.net/
- https://github.com/opensourcedesign
- https://discourse.opensourcedesign.net/

and then there are the:
- https://twitter.com/opensrcdesign
- https://www.facebook.com/opensrcdesign/ ([#27](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/27))

WDYT?

**Comment by razetime** [comment]
Sorry Valica, but on facebook, the domain name opensource design was taken,
because there was http://open-source-design.com that took the name.

Medium does not allow you to choose your own domain name , so we cannot change
that.

Changing our username on GitHub would be tedious, and would be annoying to
people who are currently working on our repos.

So, let's leave this alone, and get on with our projects in open source , and
spreading word.

> On Nov 22 2015, at 2:17 pm, Ecaterina Moraru (Valica)
&lt;notifications@github.com&gt; wrote:  

>

> Hi,

>

> I think we need to agree on what naming we should use when creating/adding
external services in the benefit of our community.

>

> For example:  
In the Medium proposal
([#17](https://github.com/opensourcedesign/organization/issues/17 "Open Source
Design on Medium" )) why is it called

>

>   * <https://medium.com/open-source-design> ?

>

> When we have:

>

>   * <http://opensourcedesign.net/>

>   * <https://github.com/opensourcedesign>

>

> and then there are the:

>

>   * <https://twitter.com/opensrcdesign>

>   * <https://www.facebook.com/opensrcdesign/> ([#27](https://github.com/open
sourcedesign/opensourcedesign.github.io/issues/27))

>

> WDYT?

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/opensou
rcedesign/organization/issues/18).![](https://github.com/notifications/beacon
/AKgUlxlT6FUYzO6l08KeaV7eICsyPZW4ks5pIXi-gaJpZM4GnE0b.gif)

**Comment by evalica** [comment]
And for future possible services? What is the "preferred" naming?

**Comment by razetime** [comment]
Mostly some thing like opensrcdesign. or opensourcedesign.

**Comment by simonv3** [comment]
On GitHub changing an organization name is actually fairly easy. GitHub does a good job of forwarding all the things. 

@razetime please leave a topic like this open for a bit longer until there is an obvious conclusion with a couple more members. I think @evalica raises a valid point.

**Comment by jancborchardt** [comment]
The intended full name is »Open Source Design«. The URL form of that »opensourcedesign«, as on the website and Github.

On Twitter we use »opensrcdesign« only because of the character limit. Facebook should ideally be /opensourcedesign but if that’s taken then /opensrcdesign is the next best thing.

**Comment by jancborchardt** [comment]
https://www.facebook.com/opensourcedesign seems dead, last post in 2012. If someone is up for it, contacting the site or Facebook to get that page would be cool.

**Comment by simonv3** [comment]
We should document who has access to each service.

**Comment by jancborchardt** [comment]
Closing as it was clarified above:

> The intended full name is »Open Source Design«. The URL form of that »opensourcedesign«, as on the website and Github.
> On Twitter we use »opensrcdesign« only because of the character limit. Facebook should ideally be /opensourcedesign but if that’s taken then /opensrcdesign is the next best thing.

The Medium and Facebook accounts are inactive and to be removed, as discussed in the relevant issues.

**Comment by simonv3** [comment]
Can we put this on the website somewhere @jancborchardt? Brand rules?

Or is that something we'll hammer out when we do the brand? Maybe during the summit?
