### ISSUE TITLE
Separate job board into its own repo

### ISSUE THREAD

**Issue by thinkxl** [opensourcedesign/organization#23]
Make the job board an application like http://jobs.remotive.io/ without using any back-end or a paid server. 

My ideas to accomplish this are:
- Using a front-end based on HTML/CSS/JavaSCript
- Pull data from the GitHub issues (scrapping them or using GitHub API), format the data, and render it on the application

This is a very simplified idea of what we talked about on IRC.

**Comment by simonv3** [comment]
Thanks for starting this conversation @thinkxl. 

Just want to point out that the job board is in its own repo here: https://github.com/opensourcedesign/jobs/ :)

**Comment by bnvk** [comment]
@thinkxl heya, thanks for your ideas. I'm closing this issue as it's a "webdev" related issue and we're trying to consolidate all of those to [opensourcedesign.github.io](opensourcedesign/opensourcedesign.github.io) repo. 

That said, I'm not quire sure I understand what you're suggesting. The jobs we have are currently stored as Markdown files and rendered by Jekyll (which was an intentional decision) as it is more robust, flexible, and portable (away from Github) down the line!

**Comment by grahamperrin** [comment]
> … opensourcedesign.github.io repo. …

= https://github.com/opensourcedesign/opensourcedesign.github.io

**Comment by bnvk** [comment]
@grahamperrin yes, I forgot the `/` at the start. Thanks.
