### ISSUE TITLE
Sourcehunt Design on SitePoint

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/organization#27]
Hi guys!

I'm proud to announce the first edition of Sourcehunt specifically focused on design. Sourcehunt is an initiative at SitePoint to promote various open source projects in order for people to jump in and contribute. It is a great way for all those who want to get involved in an open source project, but are struggling to find the right one.

With Sourcehunt Design edition we specifically aimed to include open source projects actively looking for design contributions, or generally open for designers to contribute.

I have mentioned OSD several times as you guys have been a huge inspiration for this.
I hope to write another edition in February, so feel free to bombard me with design friendly open source projects :)

Enjoy!

http://www.sitepoint.com/talented-designer-sourcehunt-needs/

**Comment by simonv3** [comment]
Heyo! I was going to suggest OpenFarm, but you've already featured it! Thanks :)

**Comment by jancborchardt** [comment]
@elioqoshi awesome! :) Especially since you mention a previous PHP contributor initiative, [ownCloud](https://owncloud.org) might be fitting as well for this here. We are very much focused on providing a top-notch but simple to use product. I’m the design lead there and we cultivate an open design process since a long time – and we’re always looking for ambitious designers to join in. :) Let me know what else you need for the project getting featured in the next edition.

Others which of course come to mind are: Mailpile (cc @bnvk), MediaGoblin, Drupal, GitLab, the Shout IRC app, Piwik and many more. :)

**Comment by Xaviju** [comment]
@elioqoshi Nice! I'd like to suggest [Taiga](https://taiga.io/) as well, where I am designer and developer. We have been trying to create a friendly open source platform for designers to contribute, and we are always happy to receive suggestions and contributions. If you think Taiga can fit in the next edition let me know what do you need. We could suggest some currently open User Stories that might fit well for juniors and advanced designers.

Thanks a lot for the initiative!

**Comment by bnvk** [comment]
@elioqoshi I'm working for the next year on security focused @QubesOS and would welcome any help from designers :)

**Comment by Xaviju** [comment]
I was just reviewing old issues to clean a bit the organization issues...
@elioqoshi should we close this one?

**Comment by elioqoshi** [comment]
Yes, thanks we can close this :)
