### ISSUE TITLE
Approve pending Open Collective expenses

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#55]
I submitted some expenses to our Open Collective at https://opencollective.com/opensourcedesign/expenses, basically all the domain stuff. :)

Mind going through and approving them @simonv3 @bnvk @belenbarrospena @ei8fdb @victoria-bondarchuk @elioqoshi @evalica? :) Also please submit any expenses you had!

**Comment by simonv3** [comment]
Done. Took me three tries to log in with the right e-mail address :P.

**Comment by elioqoshi** [comment]
I don't think I can approve them. Should I be able to? ping@elioqoshi.me it is

**Comment by evalica** [comment]
Hi @jancborchardt Thanks for adding the expenses. 
1. Would be great if in the title of the expense you could also mention the period of the renewal. Is it per year? For example, are we covered for 2017? 

2. I didn't know we also have the opensourcedesign.io domain. Is this something we plan to renew in the future? Are we using it? Especially since I see it's double in price. 

3. We currently have 163.45$ and the sum of expenses is 163$. So we will be left with 0.45$. Again related to 1, how much time would we need to gather the amount for the next domain renewal? 
3.1 Also I guess the stickers expenses are on hold since we have logo problems and also someone offered to help with the expenses.

**Comment by elioqoshi** [comment]
I agree that we don't need the .io domain.

**Comment by evalica** [comment]
4. Also not sure why the receipt value differ from the displayed value. It that a commission we give to Open Collective?

**Comment by simonv3** [comment]
That last one - open collective shows in dollars, while the receipts are in euro. Those rates actually seem pretty low. Is the euro that low these days?

**Comment by evalica** [comment]
As a feature for the Open Collective website, they should show the rate value, because it might matter when we make the reimbursement.

**Comment by bnvk** [comment]
> I agree that we don't need the .io domain.

Yep, I agree as well.

**Comment by belenbarrospena** [comment]
I can't see the receipts either, but nothing I can see raises any alarm bells. And thank you @jancborchardt for taking care of the hosting up to now! :)

**Comment by evalica** [comment]
So OpenCollective run an information mail about the fees: "PayPal fees (2.9% + $0.30) will be added to expenses that are paid through Open Collective. So, if you approve an expense for $100, we'll deduct $103.20 from your collective and reflect that on your ledger."

So from what I understand that's why there was the difference in the value displayed. It includes the fee. 

Now I don't think they make a difference between currency. So if anybody also wants to include the currency difference, make sure to specify the exchange rate and the according value.

**Comment by jancborchardt** [comment]
- Yes, the additional price is the PayPal fee automatically added by Open Collective
- Agree we don't need the .io domain, sorry for spending money on that but I wanted to initially make sure we have some major ones since .com and .org were taken. But since we have .net we don't need .io. Will just let it time out then. Let's see if yet-another-open-design-project buys it …
- Domain prices are always for a year, yep :)
