### ISSUE TITLE
Open Source Design Summit - Ideas & Brainstorming

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/organization#57]
I'm gonna break the ice since we have been mentioning it all around inofficially, but there is no trackable discussion of this yet.

Sooner or later, we want to have an OSD Meetup/ Summit to meet up for a few days and catch up on everything OSD. I'm a fan of the Tor Meeting format, where the first 4 days are team meetings, and the 2 other days are public hackathons. We could do something similar, with 2-3 team working days and an additional day for people interested in OSD. We could even tick off jobs on the job board on the last day.

I think we could be able to get this going by the end of this year. The biggest problem here would be funding travel & accommodation, which we might figure out with our companies I suppose (Mozilla could sponsor me for example).

For various reasons, I think Berlin would be perfect to hold the meetup (let's make sure to support @simonv3 in coming though). We could probably host the event at the Mozilla or Wikimedia offices.

What do you think?

I'm excited to help plan this :)

**Comment by jancborchardt** [comment]
Yeah, let’s get this started!

I’d agree Berlin is the prime location since many of us are here (like @bnvk @jdittrich @Incabell @bbalazs @danilapellicani @Kriesse @Fischaela @mrflix @ScintillaLuz @TamaraAtanasoska, me and others). Lots others are in central Europe, and some we need to get in from Alaska. ;)

I think very important for us is to actually work on defining what we want to do, set up teams and start working on it. Like for the job board, improving the website, writing articles, or getting open source into design conferences, or mentoring at design universities, etc.

More importantly than to just »tick off jobs on the job board« is to build this community together and widen its activity & reach. And that’s what an Open Source Design Summit should be focused on. :)

**Comment by elioqoshi** [comment]
Agree with that. Let's not forget to also plan some fun social activities in.

We should focus on exponential things at the summit indeed, as you mentioned.

We might want to focus our Open Collective on getting funds for this maybe.

**Comment by elioqoshi** [comment]
There is a sliiiight chance Mozilla can sponsor financially here, if we pitch it right. Less than $1k though from what I can judge (if it's DevRel).

**Comment by simonv3** [comment]
This sounds like it would be awesome and fun. 

I know I would be much more likely to come if it was some time in fall (I'll already be on the East Coast in October, so that would be good timing for me), if it was more than 2-3 days so that it's worth the 30h travel time ;), and if some of my ticket can be paid for (but this is not a hard limit, it's just expensive to fly to Europe from Alaska).

I think it's a great idea to do a funding drive on open collective to fund this. I don't know if we'll get a lot of money from it though (surprise me, please!). Are there any places we could get a grant for this? EU gov grants maybe?

**Comment by studiospring** [comment]
Meatspace meetups are the best kind of meetup, but open source is by its nature distributed. Will the minutes of the meetup be shared later? Is it possible to have a follow-up/simultaneous meetup online (irc?), so that others can get involved?

**Comment by simonv3** [comment]
@studiospring yes and I think that's absolutely critical to both of those things.

**Comment by elioqoshi** [comment]
Can we create a new repo for the summit to start planning there?

**Comment by jancborchardt** [comment]
Again – the amount of repositories is already confusing, we scramble to find what’s in organization and what in events etc. What does an entirely new repo give us that we can’t do here via a Issues and Wiki? :)

**Comment by elioqoshi** [comment]
Yeah of course. Wiki? Do we have a Wiki?

**Comment by elioqoshi** [comment]
I created the summit label and added it here. We can use it on other issues related to this I suppose. What do you think?

**Comment by rskikuli** [comment]
Great idea. I would also propose Albania or Greece. In Albania there is a team that can help with the logistics. In addition if participants combine also some vacation days with the summit it gives more value to the whole process. In Greece i propose Syros island as a place with a lot of students that are into industrial design, but that could also help with the logistics.

**Comment by elioqoshi** [comment]
We would be happy to host you on the seaside of Albania/Greece as well, if people would like to :)

**Comment by bnvk** [comment]
I think we *need* to schedule this so @simonv3 can attend- the rest of us 
Europe-OSD crew meetup IRL quite regularly. @simonv3 could you hit East coast on 
your way home?

I've created a Doodle (nifty for collaborative date/time issues) 
but set it as "invited by email only" as I think we should scope the initial 
date planning to core OSD people, as well as people from other groups / graphs
who have been supportive / interested in OSD who might be keen. Among those:

- Kriesse, an early OSD supporter fan / CSS(conf) magician
- Simply Secure folks Ame & Scout
- IF Project's Sarah Gold
- FSFE contact who gave us the assembly at 33c3

http://doodle.com/poll/y9iybqv628r3q2xd

If I missed anyone, add their username / email and I can add it to the Doodle.

> We might want to focus our Open Collective on getting funds for this maybe.

Yah, we can make sure to save 50-75% whatever of a month's funding, or perhaps
making a small micro-campaign on GoFundMe with clearly stated expenses goal? 
@elioqoshi is Mozilla able to donate to public (group) funding things like 
that?

> I’d agree Berlin is the prime location 

BIG +1 to this as a location :D but like @rskikuli suggests, Albania could
be cool since Elio + crew are there. I'm less keen on Greece or places non-core
team / natives are from.

> I think very important for us is to actually work on defining what we want to
> do, set up teams and start working on it.

Great point @jancborchardt I'd suggest either a markdown file in the events
to cull (finalized) info. But a summit specific repo might make sense- to 
collect information specifically for the event + from the event. Additionally, 
people interested interested in **just** the summit can subscribe to it.

**Comment by elioqoshi** [comment]
@brennan Good to see this going :)

I only have a problem with the Core Members thing. Who decides who is one and who not? I get where you are coming from, but that might be exclusive for some people (although by accident). Maybe we should state this in the bylaws or similar to have some partially official  OSD Membership? Again, without overcomplicating stuff, but we need to have a process on enabling people to get involved in such decision making and be clear who has the "right" to vote and stuff.

@simonv3 should be definitely able to be there and I'd propose we try to cover his travel, if we are able to.

>Yah, we can make sure to save 50-75% whatever of a month's funding, or perhaps making a small micro-campaign on GoFundMe with clearly stated expenses goal?

Might be cleaner and more convenient to do this one time off with GoFundMe. +1 to that.

>@elioqoshi is Mozilla able to donate to public (group) funding things like that?

Pretty sure they are. I have received payments personally for community events in the past (which were no entity). Worst case scenario, I can invoice via Ura.

>BIG +1 to this as a location :D but like @rskikuli suggests, Albania could be cool since Elio + crew are there. I'm less keen on Greece or places non-core team / natives are from.

The good thing about Albania is that while flight connections are a bit expensive and not so easy as Berlin, costs for hotels, transportation and food are pretty cheap. Accommodation ranges from 10 EUR for a hostel, to 20 EUR for a basic hotel single room and 30-40 EUR for a decent room.

I would be able to ensure we can get the venue for a reasonable price, aiming at 50-100 EUR per day.
Big plus here would be that it might be an alternative place to meet, since there is a lot going on in Berlin, and Tirana, Albania has a more peaceful pace. Food is great and well, we have beaches just 30min far away from Tirana :P

**Comment by elioqoshi** [comment]
If we do it in Berlin we might do it at the Onion Space as well, with the UX Team at Tor making more progress. @lindanlee might be interested to be at the summit as well

**Comment by ei8fdb** [comment]
Good to see the discussion happening. 👍 

## Format

From @elioqoshi 
> the first 4 days are team meetings
> the 2 other days are public hackathons

I'm a little familiar with the Tor meet-up format too, and think it might be useful to try. I wonder if it would translate to what we're trying to do with the group? 

### Agenda/what would happen
IMO, the Tor meetup is for *a defined list of projects (browser, network..etc) where are we are a bit more at the stage of getting a bit more organised..a little like what @jancborchardt :

> actually work on defining what we want to do, set up teams and start working on it. Like for the job board, improving the website, writing articles, or getting open source into design conferences, or mentoring at design universities, etc.
> More importantly than to just »tick off jobs on the job board« is to build this community together and widen its activity & reach. And that’s what an Open Source Design Summit should be focused on. :)

I think this is a good broad list of topics to start with.  

I felt we missed an opportunity at FOSDEM to discuss topics that @jancborchardt mentioned above. We could have had a good few hours to define things. I really enjoyed a totally impromptu discussion with @evalica and @victoria-bondarchuk standing in the FOSDEM canteen on Saturday. I would have liked that to be a broader discussion.

> Can we create a new repo for the summit to start planning there?

As @jancborchardt said is there a need for another repo? If needed then OK, but personally I'd prefer to see this discussed either under this repo or possibly more logical would be the events repo? A wiki section in the events or org repo would be easier to follow (for me).

## Location
In terms of location for me personally, anywhere western/central Europe would make it easy for us.

### Getting @simonv3 here

I also support the idea of making it easier for @simonv3, and other far away OSD members  to attend. 

## Finances 
In terms of finance, my only request is that we deal with finances as transparently as possible. I think we should try and get support from organisations in open source. 

It would be even better if we could promote donations to the Open Collective from people posting design jobs? Every £€$50 would make a difference..

Just a few thoughts..

**Comment by elioqoshi** [comment]
@ei8fdb Make sure to fill out the doodle :)

I'm in favor of 3 days core team meetings, 1 public hackathon day and 1 additional day made out of social activities and sight seeing (so we can tune down properly).

Agreed with the finance transparency as well.

@jdittrich Is there any way we can request funding from Wikimedia for this? I know of Rapid Grants up to 2000 USD but not sure what metrics we could add

**Comment by elioqoshi** [comment]
Because my fingers were too itchy so I gave this a go. Should be fine regardless what direction we take regarding the OSI Logo I'd say. What do you think?

![osd summit logo 1](https://cloud.githubusercontent.com/assets/5436686/23512249/4c2d7c4e-ff60-11e6-8914-314d1eb20db2.jpg)

**Comment by bbalazs** [comment]
I just talked to my boss. If this is going to happen in Berlin and we have no trainings during the time, we can offer our training facilities for the meeting. This would include beer and other drinks as well... This would be here: KDAB, Reuchlinstraße 10-11, 10553 Berlin

**Comment by bnvk** [comment]
Daaaaang @elioqoshi I love that logo. You're a logo-meister, seriously ;)

I totally vote YES in favor of using this logo!

**Comment by jancborchardt** [comment]
@elioqoshi awesome logo, yeah! :) I would only play a bit more with the font – use different weight for »Summit«. Any maybe different linebreaks, or also use »Open Source Design Summit« instead of all-caps for readability (and because we do that in our current logo too. :)

**Comment by Incabell** [comment]
There is a chance Wikimedia could cover some funding for this. Especially if this would take place in our offices. This is not smth me or Jan can do though, because the request needs to come from a community member not employed by WMDE. 

I don't know the exact process but you'll have to write communtiy@wikimedia.de and explain what it is we're doing and how it's helping to make more knowledge freely accessible in a sustaiable way (documentation of some sort). Can't at all estimate what the chances are and how high the funding would be but definitely worth a try IMO.

**Comment by elioqoshi** [comment]
Thanks for the kind words!

@jancborchardt thanks for the feedback. In fact on the website it's in all caps. so I was trying to be consistent hjere. The linebreaks are terrible though, but it might work better when the year is added.

Proposing also a vertical version if it's needed.

What do you think?
![osd summit logo 2](https://cloud.githubusercontent.com/assets/5436686/23542890/d8ae317e-ffef-11e6-8ab4-8e75fe227c7b.jpg)

**Comment by gsambrotta** [comment]
@elioqoshi cool logo!! I really like it! In my opinion, second version is a bit too dark for me. It lose all the attention on the logo icon which is really nice and unique.

**Comment by elioqoshi** [comment]
Thanks @gsambrotta :)

Both versions are pitch black so not sure if you are referring to color, or presence of the individual elements. Making the icon bigger would detract attention from the wordmark I'd say

**Comment by jancborchardt** [comment]
@elioqoshi this version is much better – but I would lose the black bar and just make the text »Summit 2017« black. And all text size should be the same, currently the vertical one has a slight difference, right?

**Comment by jancborchardt** [comment]
@elioqoshi also, on the website it never was all-caps ;) http://opensourcedesign.net/

**Comment by elioqoshi** [comment]
>@elioqoshi also, on the website it never was all-caps ;) http://opensourcedesign.net/

It is on the menu bar once you scroll down. Check it out (which is another problem, since both versions are not consistent).

**Comment by elioqoshi** [comment]
@jancborchardt what do you think about this? 
![osd summit logo 2](https://cloud.githubusercontent.com/assets/5436686/23551921/6b9ba77c-0019-11e7-89ab-9f537d2a0379.jpg)

**Comment by gsambrotta** [comment]
This is awesome!! :) both of them

**Comment by Incabell** [comment]
Love the new version! @elioqoshi 

And yes, I would definitely suggest to apply for a grant!

**Comment by evalica** [comment]
I'm glad that we have people interested in the Summit and so many generous ideas and offers. 

My main concern is the length of the Summit proposal. For some (like me) it might be hard to spend 5 days in Berlin (maybe it would be more acceptable that 2 of them were the week-end, since I need to take holidays in order to attend), but maybe I'm it's just me. Still 3 days sounds acceptable. I guess it all depends on the schedule and activities we want to do. if we have 'content' for 5 days than it will be great. 

The logos are really nice.

**Comment by bnvk** [comment]
> For some (like me) it might be hard to spend 5 days in Berlin (maybe it
> would be more acceptable that 2 of them were the week-end, 

Good point. Thanks for stating this. I was actually thinking (once we agree
on the week) that we run a slightly more 3 - 5 specific poll to take into
account things like this!

**Comment by jdittrich** [comment]
>  For some (like me) it might be hard to spend 5 days in Berlin 

One approach could be having a 2 days more intense conference/communication centered and an additional 3 design/hack days.

**Comment by elioqoshi** [comment]
If you check my proposal in the schedule issue ( https://github.com/opensourcedesign/organization/issues/66#issuecomment-284077488 ) you can see that the main days are Saturday/Sunday in both proposals, so I think the 5 day plan doesn't change much even for those who might not attend all days, apart the fact that the pace will be a bit more relaxed.

**Comment by peapoll** [comment]
I really like that logo, but I think it needs some color splash to freshen the logo up a little. I made a example and provided some suggested colors to play around with. Make use of it as you wish! :)

![logo_color](https://user-images.githubusercontent.com/30602609/28790474-7f5ac7bc-7629-11e7-8c00-b8ade19c0f1f.png)

SVG:
[logo_color.svg.zip](https://github.com/opensourcedesign/organization/files/1188378/logo_color.svg.zip)

**Comment by evalica** [comment]
Closing since the event has passed!

**Comment by elioqoshi** [comment]
And 2018 edition discussion goes here :)
https://github.com/opensourcedesign/organization/issues/103
