### ISSUE TITLE
Create various group@opensourcedesign.net email forwarders

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/organization#63]
Cases emerge where conversations regarding OSD start to happen in email channels, and these conversations stay in email channels amongst *just* the people initially involved. I would very much like to offer a way to loop others in that is efficient + privacy respecting such as group forwarders. Some suggested addresses are:

- archive@opensourcedesign.net (for people to use as Bcc whenever they want)
- core@opensourcedesign.net (for discussing things that could have big impact but need lower signal / noise ratio & more privacy than public, e.g. DesignOpen.io thread)
- events@opensourcedesign.net
- tasks@opensourcedesign.net (if people want to do small tasks and such)
- conduct@opensourcedesign.net (code of conduct violation reporting)

I can help you do this via various email services I'm familiar with. @jancborchardt you have access to the domain name, yes?

**Comment by jancborchardt** [comment]
I would like to keep as many interactions in the open as possible, so I would say we should do this on a very specific case-by-case basis.

For example, can you list the reasons we need these domains? I understand conduct@ for reporting violations of the code of conduct, and events@ would be useful for contacting venues. Tasks and so-called »core« discussions should be public though if we want to grow our community. :)

**Comment by elioqoshi** [comment]
I do think we need some privacy when discussing things like working together with OSI or other "Open Design" groups as the topics can be quite controversial and missunderstood if not looped in right. 

@bvnk @jancborchardt I think you know what cases I meant here as an example

**Comment by ei8fdb** [comment]
Totally agree with @jancborchardt's points. 

Yes email addresses/forwarders are useful for dealing with interactions with people/companies outside OSD, but I don't see why tasks and decisions can't be handled in a Kanban board/issues tracker.

All (most) of the work process stuff I do in the gov department I work at is held in a Trello board(s). People can then see whats there.

**Comment by elioqoshi** [comment]
>Yes email addresses/forwarders are useful for dealing with interactions with people/companies outside OSD, 

I think that's the use case Brennan described here.

**Comment by evalica** [comment]
I prefer doing things in the open and I don't think we need the above mailinglists.

**Comment by simonv3** [comment]
What if we had an e-mail address that automatically posted a github issue to a "contact" repo when it receives an e-mail?

Main concern there is spam, but if it's gmail it might be pretty good at filtering out the spam.

**Comment by elioqoshi** [comment]
>I prefer doing things in the open and I don't think we need the above mailinglists.

I assume that doesn't mean that we are discussing this to close up some discussion? There is a fine line between transparency and privacy, especially for controversial topics which are related with relationships between people or even drama, which I'd rather not have on a public forum, frankly.

I'd rather say that openness is like chocolate. It's great most of the time and there is always place for it. But sometimes it's not the right time and place for chocolate :)

**Comment by bnvk** [comment]
Since core@ exists now, that is sufficient so closing (for now)!

**Comment by jancborchardt** [comment]
Since we are transparent about all our decisions, here’s the people currently being part of this core@ forwarder, and their Github handles. Next to it also the reasoning for their addition to this list, as reference and also to get to know each other more :) (let me know if I forgot anything)

- Belen Barros Pena @belenbarrospena - co-starting this initiative, co-organizing the first FOSDEM Open Source Design rooms, setting up the job board form
- Brennan Novak @bnvk - co-starting this initiative, setting up website, job board, and other infrastructure like chat.opensourcedesign.net
- Charlie Kritschmar @Incabell - co-organizing the regular Berlin Open Source Design meetup, co-organizing the Open Source Design Summit Berlin
- Ecaterina Moraru @evalica - organizing this years FOSDEM Open Source Design room, long-term involvement
- Elio Qoshi @elioqoshi - pushing design quality in open source, co-organizing the Open Source Design Summit Berlin
- Jan-Christoph Borchardt @jancborchardt (me) - co-starting this initiative, co-organizing the first FOSDEM Open Source Design rooms, setting up Github & Twitter & Open Collective, applying with FSFE & OSI
- Jan Dittrich @jdittrich - co-organizing the regular Berlin Open Source Design meetup
- Simon Vansintjan @simonv3 - work on the website, co-maintaining Github and Twitter accounts
- Victoria Bondarchuk @victoria-bondarchuk - co-organizing the two FOSSASIA Design tracks

As per discussion on https://github.com/opensourcedesign/organization/issues/63 this is strictly for stuff we can’t talk about in the open, which will occur very rarely. But some examples:

- It helps reduce bottlenecks when someone of us gets sent an email which is about Open Source Design as a whole but not fit to discuss on the issue tracker:
  - When OSI sent me the note about changing the logo – although then we took it into the open, which made it properly documented and easy to understand.
  - When we have mail exchanges with other people in the general open source + design field about collaboration, involving a more diverse group can be conducive to discussion.
- Code of Conduct violations.
- Applying to the FSFE or OSI as affiliate / associate to have one main contact email address.

This is absolutely NOT for anything which belongs in the open. I expect us to use it only a few times a year. :)

**Comment by simonv3** [comment]
Should we list the above somewhere more publicly like on our website?

**Comment by jancborchardt** [comment]
@simonv3 I think so, at least on the Code of Conduct report page. Otherwise I’d still prefer that we don’t refer that often to a »core« group except when necessary.
