### ISSUE TITLE
preparations for use of Discourse for discourse.opensourcedesign.net

### ISSUE THREAD

**Issue by grahamperrin** [opensourcedesign/organization#79]
Spun off from https://github.com/opensourcedesign/resources/issues/16 (Free-as-in-freedom tools for Designer Dev communication and creation), https://github.com/opensourcedesign/organization/issues/69 (Cross-Project-Communication and community: Creation of Mailinglists?) and https://github.com/opensourcedesign/organization/issues/73 (Strategy for OSD's goals, user base, platform and growth): 

- I'm preparing for free hosting of a [Discourse](http://www.discourse.org/) instance for Open Source Design. 

From preliminary advice, which I received via e-mail, two key points: 

> … follow the _discourse.example.com_ sub-domain convention. …

– and: 

> … we do not support Cloudflare and other such middleman services. Please point to us directly. … 

## Domain name and address

Given the open nature of OSD community developments, I assume that it will be OK to use – from the outset – an address that can endure: 

- `https://discourse.opensourcedesign.net`

Please, does anyone foresee a problem with use of that address? 

(If not `discourse.opensourcedesign.net` then a temporary domain name may be used.)

Who should be my point of contact for co-ordinated changes to DNS? 

## Related

Other issues, in this repo, where subscribers may wish to be aware of the Discourse development: 

- https://github.com/opensourcedesign/organization/issues/12 (Bylaws) with reference to http://opensourcedesign.net/by-laws/
- https://github.com/opensourcedesign/organization/issues/18 (Domain consistency)
- https://github.com/opensourcedesign/organization/issues/54 (Build a nicer "Get Involved" page)
- https://github.com/opensourcedesign/organization/issues/63 (Create various `group@opensourcedesign.net` email forwarders)
- https://github.com/opensourcedesign/organization/issues/67 (Cooperate with openusability.org)

**Comment by jancborchardt** [comment]
Cool on taking the initiative here to make something out of the discussion @grahamperrin! :)

I do think Discourse will be good to give a place to the broader Open Source Design community. We do use/abuse Github Issues for a lot of these things at the moment. Which has its upsides because it’s in one place, but also the downside that it might not be well accessible for lots of people not yet familiar with Github, and also that it mixes `discussions` and `work`.
Now while we should be focused on getting things done, I think giving a place to open discussions is essential too.

Just looping in @simonv3 @belenbarrospena @bnvk @evalica @elioqoshi @victoria-bondarchuk @ei8fdb @jdittrich @Incabell – what do you think?

**Comment by elioqoshi** [comment]
Looking forward to this. Discourse is great once you get used to it. I just hope we refrain from having important conversations on GitHub afterwards.

**Comment by grahamperrin** [comment]
Thanks folks. For now, I suggest a tight focus on preparations such as: 

- agreement of the conventional address
- DNS

– so that this Discourse-specific issue can be closed, in due course, without difficulty. 

For as long as this issue `#79` will remain open: issues such as #69 should be good for ongoing discussion of blended use of a variety of tools.

**Comment by jancborchardt** [comment]
So, usually we go with generic subdomains and not product-specific ones like http://chat.opensourcedesign.net. So I’d go with http://forum.opensourcedesign.net, or http://community.opensourcedesign.net or talk. instead of `discourse.`

What do you think?

**Comment by grahamperrin** [comment]
Thanks. 

`community.opensourcedesign.net` looks good to me, and it's consistent with the example for the standard option at https://payments.discourse.org/buy/ – 

![discourse - hosting plans](https://cloud.githubusercontent.com/assets/192271/24332173/df2f247a-1239-11e7-99fb-25f09e299e5b.png)

– I wonder whether the plea to "follow the follow the _discourse.example.com_ sub-domain convention" relates to the exceptional offer of free hosting. I'll let someone from Discourse advise on this point.

**Comment by jdittrich** [comment]
> Whilst community.discourse.net looks OK, I reckon that forum.opensourcedesign.net will be more memorable and easier on the fingers.

+1 One could say that our Github or IRC activities are "Community", too, so I like "forum", it tells what to expect pretty well.

**Comment by erlend-sh** [comment]
> I wonder whether the plea to "follow the discourse.example.com sub-domain convention" relates to the exceptional offer of free hosting. I'll let someone from Discourse advise on this point.

Yes, this is a requirement for our free hosting. It's the only piece of branding we apply to the free plan. Aside from this, the forum is 100% whitelabeled and can be customised to your liking.

**Comment by simonv3** [comment]
Since it's a requirement I guess it's what we'll do!

**Comment by grahamperrin** [comment]
Thanks. For now I'll assign this issue to myself, I need to send one or two more e-mails before proceeding with form-filling. 

**To whoever will be able to make (or arrange) changes to DNS**: 

- please be prepared to assign this issue to yourself

– or take it now, if you prefer :-)

**Comment by jancborchardt** [comment]
@grahamperrin I have the domain – just let me know when it’s set up and what I need to change and I’ll do it. :) You can also send me an email at: hey at myusername dot net – I’ll see that quicker.

**Comment by grahamperrin** [comment]
> … one or two more e-mails before proceeding …

No response, yet, to the first. 

----

I have plenty of free time this weekend so I went ahead with the application. From the resulting e-mail, **one action point**: 

> - Add a DNS CNAME record that points discourse.opensourcedesign.net to opensourcedesign.hosted-by-discourse.com

Also, for reference: 

> … After that,
> 
> - We’ll automatically monitor for your DNS update, and get your new Discourse site provisioned as soon as we see the change go live. DNS changes can take a little while to propagate.
> - Once your Discourse is ready, you will get another email inviting you to sign up and become an admin.
> - …

**Comment by simonv3** [comment]
Hey @grahamperrin I'm not sure I get all the context of your update. Have you been in touch with Discourse?

**Comment by grahamperrin** [comment]
Yep, I made the application this morning, which led to an e-mail from the Discourse Team.

**Comment by jancborchardt** [comment]
And before we put the forum public it would be good to have some discussion about how we use it:

- Github remains the platform to talk about specific focused work items.
- Discourse is more for general discussion, fostering the larger community.

I think this separation is important so we don’t lose focus, but also nurture the greater Open Source Design community.

For example, from the monthly Open Source Design calls we should post the minutes in the Discourse, but when individual work items relate to stuff which needs to be done here we should open issues on Github.

For tags we could use:
- City names, like we do for the Twitter lists https://twitter.com/opensrcdesign/lists and Github teams https://github.com/orgs/opensourcedesign/teams already
- `Meetings` for minutes
- `Tools` for discussion and exchange on tools → should go towards building opensourcedesign.net/tools for listing them
- `Projects` for discussing different projects and how to get involved for example → should go towards building opensourcedesign.net/projects as a showcase
- `Conferences` for checking out which conferences we are at. This should of course be reflected at http://opensourcedesign.net/events/


What do you think @simonv3 @evalica @victoria-bondarchuk @bnvk @elioqoshi @jdittrich @Incabell and others? :)

**Comment by evalica** [comment]
I would use Discourse more like a way to talk asynchronous. We have IRC for synchronous, we have GitHub for work and tasks, but if someone has some ideas or wants to brainstorm she should use Discourse. 

We shouldn't use it as a wiki. If we want summaries of the meetings we could post them on website or in the Github wiki, as a reference. Everything that is final should go on GitHub->Site. Now is unclear if we can't discuss anymore on the GitHub issues and I would resist a bit. 

I see Discourse more for beginners or people that don't like GitHub :) to be honest I don't know how we will use it. I guess it will be organic, but we still need to promote it / use it if we want others to feel encouraged to use it. 

I see it more as an experiment, since I don't think we really had a problem to solve. But since I haven't use the product I'm curious to test it. I hope it will encourage more non-technical designers contributions. 

I'm sure people will be confused where we should talk or do stuff, if one place or the other, but we will fix this in time.

**Comment by grahamperrin** [comment]
We now have http://discourse.opensourcedesign.net (thanks to Jan-Christoph) but I do not yet have the initial admin account, so people should please **refrain from signing up or logging in**. 

@jancborchardt for security, please, will https://discourse.opensourcedesign.net be possible?

**Comment by erlend-sh** [comment]
> for security, please, will https://discourse.opensourcedesign.net be possible?

All open source sites get HTTPS for free. It's been queued for your site ;)

**Comment by grahamperrin** [comment]
> tight focus 

From my point of view two issues are outstanding: 

1. logo (referenced above)
2. joint administration (I wrote to someone a few days ago)

– then the forum itself can be used to discuss how the forum should be used. 

In the meantime I should encourage attention to issues such as #69 and #73 so that meta discussions do not proliferate :-) 

Thanks

**Comment by simonv3** [comment]
@grahamperrin so can we sign up? I think we're fine to sail without a logo on the forum for now?

**Comment by grahamperrin** [comment]
Over to #73 please.

**Comment by grahamperrin** [comment]
Cross reference https://github.com/opensourcedesign/organization/issues/68#issuecomment-292762390, a preview of how one of the logo options _might_ appear in the forum: 

![logo-hexagon-2017-03-09 option in context](https://cloud.githubusercontent.com/assets/192271/24834593/69c09fc6-1ce2-11e7-9e54-5c223725b4ab.png)

Over to #68 for comments on logos, please; and bear in mind that the context above is experimental. Thanks.

**Comment by studiospring** [comment]
I'll be using this issue to keep everyone abreast of developments in the Discourse forum until members here have an opportunity to sign up to the forum. At present it is invite only and there are some areas which are not visible to the general public.

Firstly, @grahamperrin has kindly asked me to be a co-administrator of the forum, which is why I am keeping everyone up to date. Things are obviously very quiet and lonely in the forum at the moment, so our most pressing task is to invite OSD members. Unless there is a better suggestion, I will create a gmail account and ask everyone to send an email to that account if they wish to sign up. Then I can send a bulk or individual invite to OSD members.

There are obviously a lot of details about the forum (and OSD in general) that are pending until OSD members join and can have a say in those matters.

**Comment by grahamperrin** [comment]
If I understand correctly: for OSD members (who use GitHub) there should be no need to _sign up_. 

## Building a Discourse community

The build should not be in isolation; I'll add to #73. 

## GitHub

The option to use GitHub for authenticated access to the forum was enabled a few days ago –

![open source design log in with github](https://cloud.githubusercontent.com/assets/192271/24835983/20d18796-1d08-11e7-827e-6e8696a095aa.png)

– and was tested by me, but re: https://github.com/opensourcedesign/organization/issues/79#issuecomment-291898667 above, I suggest **not** taking that option until after it has been improved to use the _github_client_secret_ for _opensourcedesign_. The need for that improvement was identified a couple of days ago – thanks @jancborchardt – with follow up yesterday, so people should be kept waiting not too much longer. 

Thanks, everyone, for your patience!

**Comment by ei8fdb** [comment]
> Github remains the platform to talk about specific focused work items.

Do we have an idea what work items are? Do we need to explain them?

> Discourse is more for general discussion, fostering the larger community.

Looking for/giving advice about research and design? Posting messages about events/jobs with links to the OSD website/other places. As @evalica said "if someone has some ideas or wants to brainstorm".

> I see Discourse more for beginners or people that don't like GitHub :) to be honest I don't know how we will use it.

From @jancborchardt and @evalica's messages I read the only things we put in GH issues is website/repo tasks and the conversations needed to achieve them. The objective is to close issues once finished?

> I think this separation is important so we don’t lose focus, but also nurture the greater Open Source Design community.

+1

> One goal is to raise the overall number of people who are involved, to also raise the number of people who become core contributors. :)

And that'll require people to become friendly with Github!

> The monthly Open Source Design calls we should post the minutes in the Discourse

I agree with @evalica this type of information should be on the website, otherwise why do we need it? ;)

> I see it more as an experiment, since I don't think we really had a problem to solve. 

I kinda agree, except we do need some place for discussion. Otherwise issues are left open..

**Comment by grahamperrin** [comment]
> … I don't think we really had a problem to solve. … 

Back to #69

**Comment by studiospring** [comment]
> If I understand correctly: for OSD members (who use GitHub) there should be no need to sign up...
 I suggest not taking that option until after it has been improved to use the github_client_secret for opensourcedesign.

@grahamperrin thanks for the clarification. In which case, invites are not really needed except to inform members who are inactive.

**Comment by grahamperrin** [comment]
A preview of how the front page of the forum might appear after things become open to the public: 

![initial](https://cloud.githubusercontent.com/assets/192271/24866461/12939110-1e02-11e7-8ad0-e4ad323c7b93.png)

After dismissing the banner: 

![after dismissing the banner](https://cloud.githubusercontent.com/assets/192271/24866460/12931190-1e02-11e7-84b5-a2c38daa61b4.png)

If you would like to propose a change of wording to the banner, please reply to https://github.com/opensourcedesign/organization/issues/73#issuecomment-292776678

**Comment by grahamperrin** [comment]
Re: https://github.com/opensourcedesign/organization/issues/68#issuecomment-293368474 here's an example of the square logo, in the context of preparations for go live of the forum: 

![square](https://cloud.githubusercontent.com/assets/192271/24933656/51e2c382-1f0f-11e7-87a1-cc8e7eec14a9.png)

Compare with the hexagonal logo, in context, at https://github.com/opensourcedesign/organization/issues/79#issuecomment-292966770 above. 

Votes in 68 please: 

- https://github.com/opensourcedesign/organization/issues/68#issuecomment-292762390 for the hexagon
- https://github.com/opensourcedesign/organization/issues/68#issuecomment-293296056 for the square.

**Comment by ei8fdb** [comment]
I'm a bit confused now. Can someone tell me if the discourse.osd is now live or not?

I've tried to register over the last 2-3 days but the Github account linkage isn't working. I see mentions of invites, but don't understand how they are sent/who needs to request one.

**Comment by evalica** [comment]
@ei8fdb the server is on, but it's not available to the public yet. There are like 5 people on it. We currently don't have the admin, so we rely on grahamperrin and studiospring. They wanted to do some prestuff, like creating some categories, decide on administrators. It should be public ASP, but we don't have control over it.

**Comment by bnvk** [comment]
I've been fully supportive of setting up and having a Discourse as a forum for general discussion pertaining to OSD, but *not* for content. Content is what our **website** is for. I don't recall this ever being something we desired doing. Regarding the Discourse platform:

- Sign up to discuss should be 100% open for any public persons
- The only aspect which should require being "invited" are admins 
- All core OSD members should be granted admin access to the platform
- The "welcome banner" should offer helpful links to all the aspects of OSD community (Website, Github, Twitter, Chat, Job Board, etc...) not repeat content on the website

Does this sound about right to you @jancborchardt @simonv3 @evalica @belenbarrospena @ei8fdb @victoria-bondarchuk @elioqoshi @jdittrich ? 

@grahamperrin @studiospring does this all make sense? Can we move forward with these parameters or is there a block for some reason?

**Comment by grahamperrin** [comment]
@bnvk yes there are blocks, some of which are being discussed in multiple channels. 

## GitHub

> … Github account linkage isn't working. …

It was suggested to me that the routine should become _opensourcedesign_-oriented. (Better that, than association with my _grahamperrin_ GitHub account. Of course I agreed.) 

Without delay I did what was required to the Discourse side of things; that's when (as I half-expected) GitHub-based authentication ceased to work. 

The part that _seems_ to be not yet done is beyond my control. Context: 

- [Configuring GitHub login for Discourse - howto / admins - Discourse Meta](https://meta.discourse.org/t/configuring-github-login-for-discourse/13745)

– step 2 was completed by me in the early hours of Tuesday morning, 11th April, less than two hours after I received what was required for the Discourse side of things. 

A few minutes later I e-mailed the _opensourcedesign_ person, 

> please proceed as directed at https://meta.discourse.org/t/configuring-github-login-for-discourse/13745

Six hours ago a more detailed explantion was shared in the forum. I'm keen for the issue to be resolved, but (as I don't wish to be pushed), I don't wish to push the person, or people, who can complete the work.

**Comment by grahamperrin** [comment]
> …decide on administrators …

In as few words as possible (I politely beg for this conversation to not span three or more channels (and attempting to follow things such as this in GitHub is _excruciatingly_ painful)): on the morning of Thursday 6th April, a core committer to OSD was asked whether they would like to be a joint administrator. I hope that we're close to progressing such things.

**Comment by bnvk** [comment]
I'm aware of these multiple channels of discussion...

> … Github account linkage isn't working. …

@grahamperrin I believe Github login / signup functions separate from normal email signup, which is what I mean with:

- Sign up to discuss should be 100% open for any public persons

One of the whole points of OSD having Discourse is so people who don't like or use Github can participate in discussions- in which case, Github signup is not needed. Additionally, if this is taking hours of configuration (and still not working), please drop Github signup for now.

> I politely beg for this conversation to not span three or more channels

Yep, this is why I am stepping in and focusing things- this needs to happen publicly, and here, as this is where conversations and decisions have been happening since 2015.

> …decide on administrators …

We do not need to "decide" on this as we have a "core" group, these people should be admins as well as you and @studiospring since you're helping set this up. I believe you already have all of our emails sent by @jancborchardt no further discussion is needed. Simple :-)

**Comment by grahamperrin** [comment]
I politely begged, and what happened. 

The public oversimplification of matters that I preferred to be private is horribly destructive.

**Comment by bnvk** [comment]
@grahamperrin what is being oversimplified? What has been horribly destructive?

I'm just trying to make progress and get to the next step of a functioning 
Discourse instance as per our community processes...

We are still really grateful for you taking the lead and making as much progress 
as you have :)

**Comment by grahamperrin** [comment]
>> … oversimplification of matters that I preferred to be private …

> … what is being oversimplified? …

With additional emphasis: matters that I preferred to be **private**. 

Again: **private**. 

Logically, and [respectfully](http://opensourcedesign.net/code-of-conduct/), I beg people to **refrain from asking "what" in public**; it simply will not be answered by me in public, and I sincerely hope that other people will – conscientiously, colletively and individually – demonstrate respect by showing comparable restraint. 

Now: the forum staff accounts can – and should – be used to expedite the preparations that could not be made in this issue :-)

----

Beyond that: I respect the closure of this issue and so, will write nothing further here.

**Comment by evalica** [comment]
I believe that **public** discussions are the base for any open source related interaction. To be honest I'm not sure what the outcome of these discussions will be, since there is a barrier/difference in the way we usually do things. We are going in circles between the preferences of X vs. Y. We should try to focus on the well being of the community.

So in order to progress, please give admin right to @bnvk and let's make the Discourse instance public in order for everyone to be able to use it.

**Comment by jancborchardt** [comment]
Thanks to @evalica for the on-point comment and for @bnvk to make the instance public. Folks, sign up at https://discourse.opensourcedesign.net and participate in the discussions.

Before we spread the word more, I’d like this private/public stuff to be resolved. For the threads which are currently private I see two resolutions, which has to be decided on a case-by-case basis on every topic:
1. It will be made public because nothing in it is actually private. Individual people can remove their posts inside if they wish. No one removes anything made by someone else.
2. It will be deleted because it is solved or contains private information which should not be made public.

And then subsequently, the private »Staff« category should be completely abolished because it encourages clique-building and »Staff«-discussions in private. This is nothing we ever needed or used so far, and would be against our tenets of openness.
