### ISSUE TITLE
Sponsoring for summit (or generally)

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/organization#97]
**Story:** As OSD we want to provide some Pizza, Stickers, younameit at our event

We talked about this at our recent call; It was briefly mentioned that:

* There are some orgs that might sponsor
* That we might not want to be sponsored by some orgs we find unethical.

**Comment by jdittrich** [comment]
A friend pointed out that poc21 had a wide range of interesting sponsors: http://www.poc21.cc/

**Comment by evalica** [comment]
Sponsoring can be done through our OpenCollective page https://opencollective.com/opensourcedesign

**Comment by Incabell** [comment]
Hey everyone! Here's my first [draft of the Förderantrag](https://de.wikipedia.org/wiki/Benutzerin:Incabell/OSDS). It's in German so anyone who can, please let me know what to fix or feel free to do so yourself. It's a wiki! I can hand it anytime we feel comfortable with it.

**Comment by evalica** [comment]
@Incabell it looks fine and ambitious :) since the event is approaching fast, hope there will be enough time for the request to be approved.

**Comment by Incabell** [comment]
alright, to not waste any more time, i will hand it in now. we can still make changes on the go.

**Comment by elioqoshi** [comment]
Super duper great job @Incabell !

As I'm not in Berlin I'm not the best to handle logistics, but I'd be happy to help with poster or stickers design if any Berliners know a good place where to print.

Again, great news, thanks for leading this!

**Comment by HeikoTietze** [comment]
> We should quickly decide what we want so I can either order catering or order food/drinks from a supermarket that we can get delivered. I want to do this latest tomorrow.

Wouldn't be enough for [Reinstoff](http://www.reinstoff.eu) but maybe [Strandbad Mitte](http://www.strandbad-mitte.de/). No idea about catering.

**Comment by evalica** [comment]
That's great @Incabell. Thanks for handling this.

For the Hotel rooms might be a bit late, since people already got reservations, but it's great nevertheless.

@simonv3 wanted ( https://github.com/opensourcedesign/organization/issues/95#issuecomment-334020951 ) to do a schedule outline and he might know how the snacks / lunch might fit in the schedule. 

Regarding stickers, that would be great. Last time we talked about it ( https://github.com/opensourcedesign/events/issues/43#issuecomment-327256486 ) we had a candidate for the sticker content in SVG format.

**Comment by Incabell** [comment]
maybe people can still cancel reservations and only lose the deposit which would still be cheaper than paying the whole thing? 

Or maybe we're lucky and someone hasn't booked yet :) anyway, the option is out there. I just need to know by Thursday if anyone wants a room because otherwise the hotel will give away the rooms to someone else.

**Comment by victoria-bondarchuk** [comment]
@Incabell Charlie this is great news! Thank you for all the work!
I and @bzz would like one room if possible. 

We arriving on 13th and if any help needed with catering please count on us!

**Comment by Incabell** [comment]
hey @victoria-bondarchuk and @bzz Is that two rooms or one for you both?

All I need is the full names of both of you and your time of arrival.

**Comment by dimitrieh** [comment]
Great to see this coming to a realisation. I am not too engaged due to high workload, but will be looking forward to attend the event. I have secured a place to sleep myself through airbnb a while ago already 😉 

see you there!

**Comment by Incabell** [comment]
I personally won't have time to order stickers or posters so if someone has time to do this it would be great if they could handle it. We can't have it directly delivered to wikiBär so either you could sent it to Wikimedia Deutschland oder have it made at a place where we can pick it up. 

If there's a possibility to buy it via Rechnung (where you can pay after receiving it) that would be best, but otherwise you'd have to pay first and then Wikimedia will reimburse you. We have 150€ bucks which can also be used for express delivery if that's what we need to do to get it in time.

**Comment by jancborchardt** [comment]
I'll look into the posters and stickers (and snall business cards advertising the job board.

Posters and business cards will be easy at a printer next to my place. Stickers I have to check, maybe possible via Flyeralarm express. If not we'll have those at FOSDEM. :)

**Comment by Incabell** [comment]
Alright, so i talked to Merle and moving money around is not possible (unlike what I had speculated in yesterday's hangout).

This means that we can't use leftover money for food on Monday and Tuesday and we can't book rooms outside of the original time frame which is Friday-Sunday. 

Sorry about that :(

I still haven't sorted out the drinks but will try and arrange that today.

No one else has requested a room so far so for next time we can learn that if we can only offer this option very close to the summit, then it would be better to put that money to use somewhere else and not request as many rooms in the budget.

**Comment by Incabell** [comment]
I have ordered some drinks for us. I hope it's enough and if not then we still have some drink money left to get some on Saturday. I was only able to order 7 crates from Rewe which is kinda strange but oh well. It'll be fiiiiiiine :D

**Comment by evalica** [comment]
Closing since the event has passed! Thanks Wikimedia for the sponsorship!
